DOCTOR_TOOLS := git make nfpm

include .kt/mk/common.mk
include .kt/mk/version.mk
include .kt/mk/config.mk
include .kt/mk/doctor.mk
include .kt/mk/nfpm.mk

.PHONY: test build run install

test: ## Run tests
	@echo "TODO: add test command"

build: ## Build binary
	@echo "TODO: build binary to dist/app/usr/local/bin/$(APP)"
	@mkdir -p dist/app/usr/local/bin

run: build ## Run locally
	./dist/app/usr/local/bin/$(APP)

install: local-install ## Install package on this machine
