DOCTOR_TOOLS := git make java mvn nfpm systemctl

include .kt/mk/common.mk
include .kt/mk/version.mk
include .kt/mk/config.mk
include .kt/mk/doctor.mk
include .kt/mk/nfpm.mk

.PHONY: test build run install

test: ## Run tests
	mvn -B -ntp test

build: ## Build Java artifact
	mvn -B -ntp clean package -DskipTests
	mkdir -p dist/app
	cp target/*.jar dist/app/$(APP).jar

run: build ## Run locally
	java -jar dist/app/$(APP).jar

install: local-install ## Install package on this machine
