DOCTOR_TOOLS := git make go nfpm

include .kt/mk/common.mk
include .kt/mk/version.mk
include .kt/mk/config.mk
include .kt/mk/doctor.mk
include .kt/mk/nfpm.mk

.PHONY: test build run install

test: ## Run tests
	go test ./...

build: ## Build Go binary
	mkdir -p dist/app/usr/local/bin
	go build -ldflags "-X main.version=$(VERSION)" -o dist/app/usr/local/bin/$(APP) ./cmd/$(APP)

run: build ## Run locally
	./dist/app/usr/local/bin/$(APP)

install: local-install ## Install package on this machine
